import { createClientFromRequest } from 'npm:@base44/sdk@0.8.38';
import { auditLedgerSnapshot } from '../../shared/ledgerIntegrityPure.js';

// Admin-only, report-only financial reconciliation. It never edits Wallet,
// SystemLedgerAccount, LedgerEntry, provider state, or game state. Ambiguous
// discrepancies remain manual-review items.
Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });
    if (user.role !== 'admin') return Response.json({ error: 'Forbidden' }, { status: 403 });

    const [wallets, accounts, entries, transactions, seamlessOperations] = await Promise.all([
      base44.asServiceRole.entities.Wallet.list(null, 5000),
      base44.asServiceRole.entities.SystemLedgerAccount.list(null, 100),
      base44.asServiceRole.entities.LedgerEntry.filter({ launch_epoch: 2 }, null, 5000),
      base44.asServiceRole.entities.WalletTransaction.filter({ launch_epoch: 2 }, null, 5000),
      base44.asServiceRole.entities.SeamlessOperation.list(null, 5000).catch(() => []),
    ]);
    const audit = auditLedgerSnapshot({ entries, wallets, accounts, transactions, seamlessOperations });

    if (audit.requires_manual_review) {
      const existing = await base44.asServiceRole.entities.IntegrityFlag.filter({
        flag_type: 'manual', severity: 'high', status: 'open',
      }, '-created_date', 50);
      const summary = `Ledger reconciliation requires review: unbalanced groups ${audit.unbalanced_groups.length}; projection mismatches ${audit.projection_mismatches.length}; duplicate operation IDs ${audit.duplicate_operation_ids.length}; missing source transactions ${audit.missing_source_transactions.length}; incomplete Seamless operations ${audit.incomplete_seamless_operations.length}; aggregate diff ${audit.aggregate_diff}.`;
      if (!existing.some((flag) => String(flag.description || '').startsWith('Ledger reconciliation requires review:'))) {
        await base44.asServiceRole.entities.IntegrityFlag.create({
          user_id: '', flag_type: 'manual', severity: 'high', status: 'open',
          description: summary,
          notes: 'Generated by checkLedgerIntegrity. Report-only: no financial projection was changed automatically.',
        });
      }
    }

    return Response.json({ ...audit, repair_available: false, repair_reason: 'Automatic repair is disabled until immutable operation-level ledger deltas and a reviewed opening-balance baseline exist.' });
  } catch (error) {
    return Response.json({ error: error?.message || 'internal_error' }, { status: 500 });
  }
});